from easydict import EasyDict

main_config = dict(
    exp_name='cartpole_dqn_multi',
    env=dict(
        manager=dict(
            episode_num=float('inf'),
            max_retry=5,
            step_timeout=60,
            auto_reset=True,
            reset_timeout=600,
            retry_waiting_time=0.1,
            shared_memory=False,
            context='fork',
            wait_num=2,
            step_wait_timeout=0.01,
            connect_timeout=60,
            cfg_type='AsyncSubprocessEnvManagerDict',
        ),
        collector_env_num=1,
        evaluator_env_num=1,
        n_evaluator_episode=5,
        stop_value=195,
    ),
    policy=dict(
        model=dict(
            obs_shape=[3, 200, 200],
            action_shape=5,
            encoder_hidden_size_list=[128, 128, 64],
            dueling=True,
        ),
        learn=dict(
            learner=dict(
                train_iterations=1000000000,
                dataloader=dict(
                    num_workers=0,
                ),
                hook=dict(
                    load_ckpt_before_run='',
                    log_show_after_iter=100,
                    save_ckpt_after_iter=10000,
                    save_ckpt_after_run=True,
                ),
                cfg_type='BaseLearnerDict',
            ),
            multi_gpu=False,
            update_per_collect=3,
            batch_size=64,
            learning_rate=0.001,
            target_update_freq=100,
            ignore_done=False,
        ),
        collect=dict(
            collector=dict(
                deepcopy_obs=False,
                transform_obs=False,
                collect_print_freq=100,
                cfg_type='SampleCollectorDict',
            ),
            unroll_len=1,
            n_sample=8,
        ),
        other=dict(
            replay_buffer=dict(
                type='advanced',
                replay_buffer_size=20000,
                max_use=float('inf'),
                max_staleness=float('inf'),
                alpha=0.6,
                beta=0.4,
                anneal_step=100000,
                enable_track_used_data=False,
                deepcopy=False,
                thruput_controller=dict(
                    push_sample_rate_limit=dict(
                        max=float('inf'),
                        min=0,
                    ),
                    window_seconds=30,
                    sample_min_limit_ratio=1,
                ),
                monitor=dict(
                    sampled_data_attr=dict(
                        average_range=5,
                        print_freq=200,
                    ),
                    periodic_thruput=dict(
                        seconds=60,
                    ),
                ),
                cfg_type='AdvancedReplayBufferDict',
            ),
        ),
        cuda=False,
        on_policy=False,
        priority=False,
        priority_IS_weight=False,
        discount_factor=0.97,
        nstep=1,
        cfg_type='DQNPolicyDict',
    ),
)
main_config = EasyDict(main_config)
main_config = main_config
create_config = dict(
    env=dict(
    ),
    env_manager=dict(
        cfg_type='AsyncSubprocessEnvManagerDict',
    ),
    policy=dict(type='dqn'),
)
create_config = EasyDict(create_config)
create_config = create_config
